const STUDENT = {
  FETCH: "STUDENT_FETCH",
  FETCH_ERROR: "STUDENT_ERROR",
  FETCH_SUCCESS: "STUDENT_SUCCESS",
};

const STUDENT_LIST = {
  FETCH: "STUDENT_LIST_FETCH",
  FETCH_ERROR: "STUDENT_LIST_ERROR",
  FETCH_SUCCESS: "STUDENT_LIST_SUCCESS",
  FETCH_ADD: "STUDENT_ADD",
  FETCH_DELETE: "STUDENT_DELETE",
};

const TEACHER = {
  FETCH: "TEACHER_FETCH",
  FETCH_ERROR: "TEACHER_ERROR",
  FETCH_SUCCESS: "TEACHER_SUCCESS",
};

const TEACHER_LIST = {
  FETCH: "TEACHER_LIST_FETCH",
  FETCH_ERROR: "TEACHER_LIST_ERROR",
  FETCH_SUCCESS: "TEACHER_LIST_SUCCESS",
  FETCH_ADD: "TEACHER_ADD",
  FETCH_DELETE: "TEACHER_DELETE",
};

const COURSE_LIST = {
  FETCH: "COURSE_LIST_FETCH",
  FETCH_ERROR: "COURSE_LIST_ERROR",
  FETCH_SUCCESS: "COURSE_LIST_SUCCESS",
  FETCH_ADD: "COURSE_ADD",
  FETCH_DELETE: "COURSE_DELETE",
};

export { STUDENT, STUDENT_LIST, TEACHER, TEACHER_LIST, COURSE_LIST };
