const STUDENT = {
  FETCH: "STUDENT_FETCH",
  FETCH_ERROR: "STUDENT_ERROR",
  FETCH_SUCCESS: "STUDENT_SUCCESS",
};

const STUDENT_LIST = {
  FETCH: "STUDENT_LIST_FETCH",
  FETCH_ERROR: "STUDENT_LIST_ERROR",
  FETCH_SUCCESS: "STUDENT_LIST_SUCCESS",
  FETCH_ADD: "STUDENT_ADD",
};

export { STUDENT, STUDENT_LIST };
