const STUDENT = {
  FETCH: "STUDENT_FETCH",
  FETCH_ERROR: "STUDENT_ERROR",
  FETCH_SUCCESS: "STUDENT_SUCCESS",
};

const STUDENT_LIST = {
  FETCH: "STUDENT_LIST_FETCH",
  FETCH_ERROR: "STUDENT_LIST_ERROR",
  FETCH_SUCCESS: "STUDENT_LIST_SUCCESS",
  FETCH_ADD: "STUDENT_ADD",
  FETCH_DELETE: "STUDENT_DELETE",
};

const TEACHER = {
  FETCH: "TEACHER_FETCH",
  FETCH_ERROR: "TEACHER_ERROR",
  FETCH_SUCCESS: "TEACHER_SUCCESS",
};

const TEACHER_LIST = {
  FETCH: "TEACHER_LIST_FETCH",
  FETCH_ERROR: "TEACHER_LIST_ERROR",
  FETCH_SUCCESS: "TEACHER_LIST_SUCCESS",
  FETCH_ADD: "TEACHER_ADD",
  FETCH_DELETE: "TEACHER_DELETE",
};

const COURSE_LIST = {
  FETCH: "COURSE_LIST_FETCH",
  FETCH_ERROR: "COURSE_LIST_ERROR",
  FETCH_SUCCESS: "COURSE_LIST_SUCCESS",
  FETCH_ADD: "COURSE_ADD",
  FETCH_DELETE: "COURSE_DELETE",
  FETCH_FILTER: "COURSE_FILTER",
};

const SEMESTER_COURSE_LIST = {
  FETCH: "SEMESTER_COURSE_LIST_FETCH",
  FETCH_ERROR: "SEMESTER_COURSE_LIST_ERROR",
  FETCH_SUCCESS: "SEMESTER_COURSE_LIST_SUCCESS",
  FETCH_ADD: "SEMESTER_COURSE_ADD",
  FETCH_DELETE: "SEMESTER_COURSE_DELETE",
};

const CLASSROOM_LIST = {
  FETCH: "CLASSROOM_LIST_FETCH",
  FETCH_ERROR: "CLASSROOM_LIST_ERROR",
  FETCH_SUCCESS: "CLASSROOM_LIST_SUCCESS",
  FETCH_ADD: "CLASSROOM_ADD",
  FETCH_DELETE: "CLASSROOM_DELETE",
  FETCH_FILTER: "CLASSROOM_FILTER",
};

const MARKS_TEMPLATE_LIST = {
  FETCH: "MARKS_TEMPLATE_LIST_FETCH",
  FETCH_ERROR: "MARKS_TEMPLATE_LIST_ERROR",
  FETCH_SUCCESS: "MARKS_TEMPLATE_LIST_SUCCESS",
  FETCH_ADD: "MARKS_TEMPLATE_ADD",
  FETCH_DELETE: "MARKS_TEMPLATE_DELETE",
};

const GRADE_LIST = {
  FETCH: "GRADE_LIST_FETCH",
  FETCH_ERROR: "GRADE_LIST_ERROR",
  FETCH_SUCCESS: "GRADE_LIST_SUCCESS",
  FETCH_ADD: "GRADE_ADD",
  FETCH_DELETE: "GRADE_DELETE",
};

export {
  STUDENT,
  STUDENT_LIST,
  TEACHER,
  TEACHER_LIST,
  COURSE_LIST,
  SEMESTER_COURSE_LIST,
  CLASSROOM_LIST,
  MARKS_TEMPLATE_LIST,
  GRADE_LIST,
};
